### ISSUE TITLE
question: how to solve error "failed to get instance admin user secret /"

### ISSUE THREAD

**Issue by SimonHeimberg** [kloeckner-i/db-operator#18]
In the log of the operator, there is the following output:
`level=error msg="Instance: name=my-db-instance failed to get instance admin user secret /"`

[In the code](https://github.com/kloeckner-i/db-operator/blob/8c301a79b3096ce1430ee292d38ef0524c14e97f/pkg/controller/dbinstance/reconcileDbInstance.go#L15) I see there should be a namespace before "/" and the name after. Why is it empy? Do I set it wrong?

my file my-db-instance.yaml:
```
apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: my-db-instance
spec:
  adminUserSecret: db-root-secret
  engine: mysql
  generic:
    host: mysql.my-db-ns.svc.cluster.local
    port: 3306
```
With `kubectl get secret db-root-secret` I get the secret. I also tried setting in my-db-instance.yaml `adminUserSecret: default/db-root-secret` and `adminUserSecret: { namespace: default, name: db-root-secret}`, but I always get the same error message.

**Comment by dabde** [comment]
Hi, 

sorry. Think the documentation is on this point outdated. on our system the dbinstance resouce is looks like this

```
apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: kwsus-review
spec:
  adminSecretRef:
    Name: {{ sec name }}
    Namespace: {{ namespace name }}
  backup:
    bucket: {{ backup bucket }}
  engine: mysql
  generic:
    host: {{ host }}
    port: {{ port }}
  monitoring:
    enabled: false
```

Will create a internal ticket to update the documentation.
