### ISSUE TITLE
Feature Request: ownerReference

### ISSUE THREAD

**Issue by mruoss** [kloeckner-i/db-operator#184]
Hey, it would be nice if the resources crated by the operator had an ownerReference (e.g. the secrets referencing the `Database` resource in [`.metadata.ownerReference`](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/)

**Comment by dabde** [comment]
hi @mruoss ,

it's already existing. Just add `cleanup: true` to the crd.

```yaml
apiVersion: "kci.rocks/v1alpha1"
kind: "Database"
metadata:
  name: "example-db"
spec:
  ...
  cleanup: true
  ...
```

fyi: We not maintain kloeckner-i/db-operator, we moved on and forked it to https://github.com/db-operator/db-operator.
