### ISSUE TITLE
Configurable database and user

### ISSUE THREAD

**Issue by bancek** [kloeckner-i/db-operator#54]
It would be nice if `db-operator` could support custom database and user name in the database resource.

Right now database and username is build like this: `<NAMESPACE>_<DB_INSTANCE_NAME>`. This also means there can only be one database per db instance per namespace.

We've added this in our fork and are open to contribute this upstream.

https://github.com/reciprocity/db-operator/commit/941783eedb77f2a88a05126cb373e8301a02911e

```yaml
apiVersion: "kci.rocks/v1alpha1"
kind: "Database"
metadata:
  name: "example-db"
spec:
  secretName: example-db-credentials
  instance: example-gsql
  deletionProtected: false
  database: customdbname
  user: customuser
```

What would be the best way to add tests for this? Duplicate all existing tests to also cover this?

**Comment by dabde** [comment]
Hi, 

I added this to our internal meeting. But the Database name is not concat by `namespace + dbinstance.name` name. It's concat by `namespace + db.name`.

so if you have a dbinstance like 
```yaml
apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: my-db-instance
spec:
  adminSecretRef:
    Name: dbinstance-secret
    Namespace: default
  engine: mysql
  generic:
    host: mysql
    port: 3306
  monitoring:
    enabled: false
``` 

you can define in one namespace several db manifest like

```yaml
apiVersion: kci.rocks/v1alpha1
kind: Database
metadata:
  name: db1
  namespace: review1
spec:
  backup:
    cron: 0 * * * *
    enable: false
  deletionProtected: false
  instance: my-db-instance
  secretName: db1-secret
---
apiVersion: kci.rocks/v1alpha1
kind: Database
metadata:
  name: db2
  namespace: review1
spec:
  backup:
    cron: 0 * * * *
    enable: false
  deletionProtected: false
  instance: my-db-instance
  secretName: db2-secret
```

and would get 2 database in your database instance called for the namespace "review1"
- review1-db1
- review1-db2

We have up to 8 databases per namespace and one db instance.

But custom naming is still a general wanted feature.
